title: Home
pages: true
files: 
  fields: true
    title:
      label: Title
      type:  text
    caption:
      label: Caption
      type:  textarea
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
  style:
    label: Estilo
    type:  text    