title: Site
pages: true
files: true
fields:
  title:
    label: Título del sitio
    type:  text
  text:
    label: Descripción para motores de búsqueda
    type:  textarea
  line-a:
    type:  line
  logo:
    label: Logo del sitio
    type:  image
    required: true
  favicon:
    label: Favicon del sitio
    type:  image
    required: true
    help: Ícono de solapa del navegador
  line-b:
    type:  line
  logoloader:
    label: Logo Pantalla Cargando
    type:  image
    required: true
  backgroundloader:
    label: Fondo Pantalla Cargando
    type:  image
  styleloader:
    label: Estilo Pantalla Cargando
    type:  text    
  line-c:
    type:  line
  logomenu:
    label: Logo Pantalla Menú
    type:  image
    required: true
  backgroundmenu:
    label: Fondo Pantalla  Menú
    type:  image
  stylemenu:
    label: Estilo Menú
    type:  text
  line-d:
    type:  line
  themebackground:
    label: Theme Background
    type:  text
    default: '#333333'
    help: 'ej. white, magenta, #000000'
  themecolor:
    label: Theme Color
    type:  text
    default: '#ff7e21'
    help: 'ej. white, magenta, #000000'
  line-e:
    type:  line
  ogtype:
    label: Tipo de aplicación redes sociales
    type:  text
    default: website
  ogtitle:
    label: Título redes sociales
    type:  text
  ogdescription:
    label: Descripción redes sociales
    type:  textarea
  ogimage:
    label: Imágen redes sociales
    type:  image
    help: JPG/PNG 500x500px
  googleanalytics:
    label: Analytics ID
    type: text
    help: Analytics Code ID provided by Google (G-XXXXXXXXXX)